### ISSUE TITLE
Could not find any code...

### ISSUE THREAD

**Issue by shaing10** [ChristianBergler/ANIMAL-SPOT#1]
Hey, thanks a lot for your contribution!
Maybe I missed something, but - the repo has detailed guides about how to use it, but I could not find any code(?)
If it is published somewhere, I'd appreciate a reference :)

Thanks in advance

**Comment by ChristianBergler** [comment]
I checked in the initial ANIMAL-SPOT version. Sorry, for being a little late during x-max/new-year
