### ISSUE TITLE
Training config file: error in default value?

### ISSUE THREAD

**Issue by liofeu** [ChristianBergler/ANIMAL-SPOT#11]
Hello,

In the config file of the TRAINING folder, about the `MAX_TRAIN_EPOCHS` it is said that "by default 500 epochs are set", however the default value is set to 1:

```################

###MAX_TRAIN_EPOCHS = Maximum number of epochs to train the network. By default 500 epochs are set. However, based on previous experience 100 to 150 maximum
###training epochs is a good number.

################

max_train_epochs=1
```

Should it be `max_train_epochs=500` instead?

**Comment by ChristianBergler** [comment]
Hello,

this is a "typo mistake" ... Should be = 500 ... Will be fixed in the next commit! Thanks for letting us know!
