### ISSUE TITLE
Do you fade-in fade-out sounds?

### ISSUE THREAD

**Issue by liofeu** [ChristianBergler/ANIMAL-SPOT#13]
Not fading in/out sounds may create energy bars over all frequencies on the spectrogram starts and ends.
Do you recommend to fade in/out the training sounds?

**Comment by ChristianBergler** [comment]
Hi, 

we did initially some experiments with fade in/out, however, there were no noticeable changes regarding the overall model performance. Currently no fade in/out is used!
