### ISSUE TITLE
Protobuf related error: cannot pickle 'weakref.ReferenceType' object

### ISSUE THREAD

**Issue by leonard-leo** [ChristianBergler/ANIMAL-SPOT#2]
I have tried to run ANIMAL-SPOT for my audio data, but encountered the error below. 

I use:
System: MacOS Big Sur, v. 11.7.2
Python version: 3.8 and 3.10 (tried both)

I installed all packages, in their respective versions, as described on your page on Github. I also prepared my data and modified the config.py file, so as to match to my data and directories.

To resolve the error, I googled it, and it appears that is related to mishandling of the multiprocessing package:
https://stackoverflow.com/questions/71945399/python-3-8-multiprocessing-typeerror-cannot-pickle-weakref-object

It appears that the error is related to the protobuf package. I also tried to run ANIMAL-SPOT using all available versions of the protobuf package (From 3.10 up to 4.21), but the error below persists.

```
Traceback (most recent call last):
  File "~../ANIMAL-SPOT/main.py", line 432, in <module>
    datasets = {
  File "~../ANIMAL-SPOT/main.py", line 433, in <dictcomp>
    split: Dataset(
  File "~../ANIMAL-SPOT/main.py/ANIMAL-SPOT/data/audiodataset.py", line 526, in __init__
    self.file_reader = AsyncFileReader()
  File "~../ANIMAL-SPOT/main.py/ANIMAL-SPOT/utils/FileIO.py", line 46, in __init__
    w.start()
  File "~../miniconda3/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "~../miniconda3/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "~../miniconda3/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "~../miniconda3/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "~../miniconda3/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "~../miniconda3/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "~../miniconda3/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'weakref.ReferenceType' object
```

**Comment by ChristianBergler** [comment]
Hi,
can you try to set the --num_of_workers variable to = 0, so that multiprocessing is not used during data loading. And yes, you are right, multiprocessing is a problem with the MAC-OS systems.

**Comment by b00leant** [comment]
I have the same error. I also tried to set `--num_workers` variable to 0 in the training config file but it persists.

MacOS Ventura
Python 3.9 + 3.8 (tried both)

**Comment by ChristianBergler** [comment]
> I have tried to run ANIMAL-SPOT for my audio data, but encountered the error below.
> 
> I use: System: MacOS Big Sur, v. 11.7.2 Python version: 3.8 and 3.10 (tried both)
> 
> I installed all packages, in their respective versions, as described on your page on Github. I also prepared my data and modified the config.py file, so as to match to my data and directories.
> 
> To resolve the error, I googled it, and it appears that is related to mishandling of the multiprocessing package: https://stackoverflow.com/questions/71945399/python-3-8-multiprocessing-typeerror-cannot-pickle-weakref-object
> 
> It appears that the error is related to the protobuf package. I also tried to run ANIMAL-SPOT using all available versions of the protobuf package (From 3.10 up to 4.21), but the error below persists.
> 
> ```
> Traceback (most recent call last):
>   File "~../ANIMAL-SPOT/main.py", line 432, in <module>
>     datasets = {
>   File "~../ANIMAL-SPOT/main.py", line 433, in <dictcomp>
>     split: Dataset(
>   File "~../ANIMAL-SPOT/main.py/ANIMAL-SPOT/data/audiodataset.py", line 526, in __init__
>     self.file_reader = AsyncFileReader()
>   File "~../ANIMAL-SPOT/main.py/ANIMAL-SPOT/utils/FileIO.py", line 46, in __init__
>     w.start()
>   File "~../miniconda3/lib/python3.10/multiprocessing/process.py", line 121, in start
>     self._popen = self._Popen(self)
>   File "~../miniconda3/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
>     return _default_context.get_context().Process._Popen(process_obj)
>   File "~../miniconda3/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
>     return Popen(process_obj)
>   File "~../miniconda3/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
>     super().__init__(process_obj)
>   File "~../miniconda3/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
>     self._launch(process_obj)
>   File "~../miniconda3/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 47, in _launch
>     reduction.dump(process_obj, fp)
>   File "~../miniconda3/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
>     ForkingPickler(file, protocol).dump(obj)
> TypeError: cannot pickle 'weakref.ReferenceType' object
> ```

Thank you for the feedback. We are looking into it and getting back to you, however, this is an OS-dependent (MAC) issue regarding the multiprocessing library which is used during the dataloading procedure - as you already correctly said.  Usually by setting --num_worker 0 (in the command line options) should set the number of threads to =1 ... So multiprocessing should be disabled.

**Comment by elenaschall** [comment]
Hi Christian,
I also have the same issue and setting the --num_workers to 0 does not solve it. Maybe you could specify in the readme that currently Animal-Spot does not work for Mac, so that we can spare the time of trying ;)
Thanks!

**Comment by ChristianBergler** [comment]
Hi Elena,
can you give it again a try? I did a fix in the utils.py so pull the current version and let me know if this works. Actually it should work for macOS.

**Comment by elenaschall** [comment]
Hi Christian,
yes it seems to work now, when I set number of workers to 0. The number of workers option is anyways not used when GPU training is enabled, right? For enabling GPU training on my MacBook Pro with M1 I had to manually set torch device to 'mps' though. However it is still training in epoch 0 (since 2 hours) with only 10,000 training samples. How long does one epoch usually take for you on which system?
Thanks!

**Comment by ChristianBergler** [comment]
The number of workers Option only affects the data loading procedure. So speeding up the preprocessing, once the training is started, it significantly differs when the training is with or without GPU. I assume you are not training with a GPU right? There is no "general duration" for system A, B, C because it depends on the hardware but also on the training data size. But without GPU it takes much longer. So i would highly recommend to train your stuff on a device with GPU support. As we reported in the paper, a mid-range NVIDIA GTX 1080 is already sufficient.
