### ISSUE TITLE
Typo in prediction config file?

### ISSUE THREAD

**Issue by adrbmdns** [ChristianBergler/ANIMAL-SPOT#4]
Hi,

In the prediction config file, the unit of the parameters `sequence_len` and `hop` should be in milliseconds or seconds?

The comment I saw in the config file says it should be in milliseconds. Please see the screenshots below.

![image](https://github.com/ChristianBergler/ANIMAL-SPOT/assets/112752904/a4117bdd-d5a8-49d9-9929-e9d5c6881be7)

But the prediction log file has a unit of seconds for those parameters, see my screen shot below. 

![image](https://github.com/ChristianBergler/ANIMAL-SPOT/assets/112752904/5d17f283-7ba7-43c2-a76e-e0fa9a05f1e1)

From the judgement based on the result I get, those two numbers should be provided in the unit of seconds. But I'm not sure, can you confirm?

Thanks.

**Comment by ChristianBergler** [comment]
Yes you are totally right, it should be seconds. I will fix that within the prediction file. Well spotted, thanks!
