### ISSUE TITLE
reference dB from 20 to 0

### ISSUE THREAD

**Issue by canihaveabravo** [ChristianBergler/ANIMAL-SPOT#7]
Hi Christian, 

How do we change the reference dB from 20 to 0?

Thanks,
Lorenzo

**Comment by ChristianBergler** [comment]
Hi Lorenzo,

Line 46 in audiodataset.py - ref db level

Hope that helps!

Best,
Christian

**Comment by canihaveabravo** [comment]
Thank you. What criteria is used to set the ref-dB level? I found that by changing to 0dB this improved the amplitude 'contrast' in my input image.

**Comment by ChristianBergler** [comment]
There is no „official criterion“. This is a data-specific parameter, dependent on the average power in your signals. In case your recording-specific spectral amplitudes are less intense, a dB normalisation with a high reference level is not optimal (and vice versa). If you look into the animal spot paper - appendix - you will find a table with all the hyperparameters. There you can see that we also changed the reference level for certain recordings. This has to be properly specified via looking at the signals. Or, as another solution: min-max normalisation. Which is also part of the new animal sport version. Available as a command line option, and does not require a pre-check of intensity levels.

**Comment by canihaveabravo** [comment]
thanks for the info
